config/routes.rb
Myapp::Application.routes.draw do
   get "sessions/login"
   get "sessions/home"
  get "sessions/profile"
   get "sessions/setting"
  root 'welcome#index'
  
  resources :users
  
  resources :messages
  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'
  

  

end

app/models/message.rb
class Message < ActiveRecord::Base
	attr_accessible :sender_id, :recepient_id, :sender_deleted, :recepient_deleted, :subject
	
	
	belongs_to :sender,
  	:class_name => 'User',
  	:foreign_key => 'sender_id'
  belongs_to :recepient,
  	:class_name => 'User',
  	:foreign_key => 'reciever_id'
  
    def mark_deleted(id, user_id)
		self.delete_s = true if self.sender_id == user_id and self.id = id
		self.delete_r = true if self.reciever_id == user.id and self.id = id
		
	end
	
	
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	attr_accessible :username, :email, :first_name, :last_name, :password, :password_confirmation
	
	before_save :encrypt_password
    after_save :clear_password
  
	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.edu\z/i
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true
    #Only on Create so other actions like update password attribute can be nil
    validates_length_of :password, :in => 6..20, :on => :create

	
	has_many :sent_messages,
  	:class_name => 'Message',
  	#:primary_key => 'user_id',
  	:foreign_key => 'sender_id',
  	:order => "messages.created_at DESC",
  	:conditions => ["messages.delete_s = ?", false]
    has_many :recieved_messages,
  	:class_name => 'Message',
  	#:primary_key => 'user_id',
  	:foreign_key => 'reciever_id',
  	:order => "messages.created_at DESC",
  	:conditions => ["messages.delete_r = ?", false]
  	
  
  def self.authenticate(username_or_email="", login_password="")

    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    password == BCrypt::Engine.hash_secret(login_password, salt)
  end
  
  
  
  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.password = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  
  
  def clear_password
    self.password = nil
  end
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  def authenticate_user
  	unless session[:user_id]
  		redirect_to(:controller => 'sessions', :action => 'login')
  		return false
  	else
      # set current_user by the current user object
      @current_user = User.find session[:user_id] 
  		return true
  	end
  end

  #This method for prevent user to access Signup & Login Page without logout
  def save_login_state
    if session[:user_id]
            redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages=Message.all
  end

  def sent
    @messages=Message.all
  end
  
  def show
    @message = Message.find(params[:id])
    
  end

  def delete
    @message.destroy
    redirect_to message_url
  end

  def new
  	@message = Message.new
    if (session[:reciever_id])
      @message.reciever_id = session[:reciever_id]
    end  
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  before_filter :authenticate_user, :except => [:index, :login, :login_attempt, :logout]
  before_filter :save_login_state, :only => [:index, :login, :login_attempt]
  
  def login
  	#Login Form
  end

  def home
  end

  def profile
  	#Profile Page
  end

  def setting
  end
  
  def login_attempt
		authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
		if authorized_user
			session[:user_id] = authorized_user.id
			flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.username}"
			redirect_to(:action => 'home')


		else
			flash[:notice] = "Invalid Username or Password"
        	flash[:color]= "invalid"
			render "login"	
		end
	end
	
	def logout
		session[:user_id] = nil
		redirect_to :action => 'login'
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 # GET /users
  # GET /users.json
  
  before_filter :save_login_state, :only => [:new, :create]
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h1>Inbox</h1>
<table>
	<thead>
		<th> # </th>
		<th> From </th>
		<th> Subject </th>
	</thead>
	<tbody>
	  <% @messages.each do |message| %>
	  	<tr>
	  		<td></td>
	      <td><a href="/users/<%= message.sender_id %>"><%= User.find(message.sender_id).first_name %></a></td>
	      <td><a href="/message/<%= message.id %>"><%= message.subject %></a></td>
	    </tr>
	  <% end %>
	</tbody>
</table>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= @message.recepient_id %>
<%= @message.sender_id %>
<%= form_for :message, url: message_path do |f| %>
	<%= f.hidden_field :recepient_id %>
	<%= f.hidden_field :sender_id %>	
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
	<%= submit_tag "Send" %>
<% end %>

app/views/messages/send.html.erb
<h1>send Message</h1>
<%= @message.recepient_id %>
<%= @message.sender_id %>
<% form_for(@message) do |f| %>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.check_box :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject :</b>
  <%= @message.subject %>
</p>

<p>
  <b>Sent By :</b>
  <h5><a href="/users/<%= @message.sender_id %>"><%= User.find(@message.sender_id).first_name %></a></h5>
</p>

<p>
  <b>Body :</b>
  <%= @message.content %>
</p>




<%= link_to 'Back', messages_path %>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" -%>
<div class= "Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

    <p>          
      Username:</br> <%= f.text_field :username%>
    </p>

    <p>
      Email:</br> <%= f.text_field :email%>
    </p>

    <p>      
      Password:</br> <%= f.password_field :password%>
    </p>

    <p>     
      Password Confirmation:</br> <%= f.password_field :password_confirmation%>
    </p>

    <%= f.submit :Signup %>
  <% end %>

  <% if @user.errors.any? %>
	<ul class="Signup_Errors">
		<% for message_error in @user.errors.full_messages %>
			<li>* <%= message_error %></li>
	  	<% end %>
	</ul>
  <% end %>
</div>


<h1>New user</h1>



<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>